### ISSUE TITLE
[HomeApplication] Can't back to first page.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#17]
When the number of items in [RotarySelector](https://github.com/dalihub/nui-demo/blob/master/wearable-samples/HomeApplication/RotarySelector/RotarySelector.cs) control is smaller (tested for 13 items - they take up two pages), there is no possibility to back to first page - by swipe gesture.

**1. The change made in sample code:** (applied [here](https://github.com/dalihub/nui-demo/blob/7622405384ac64471989f511666b455f348776be/wearable-samples/HomeApplication/NUIWHome.cs#L101))
```
diff --git a/wearable-samples/HomeApplication/NUIWHome.cs b/wearable-samples/HomeApplication/NUIWHome.cs
index e451ae5..152a8db 100755
--- a/wearable-samples/HomeApplication/NUIWHome.cs
+++ b/wearable-samples/HomeApplication/NUIWHome.cs
@@ -99,6 +99,10 @@ namespace NUIWHome
                     String FullFileName = File.FullName;

                     imageFileList.Add(new CommonResource.ResourceData(FileNameOnly, FullFileName));
+                    if(imageFileList.Count >= 13)
+                    {
+                        break;
+                    }
                 }
             }
             imageFileList.Sort(delegate (CommonResource.ResourceData A, CommonResource.ResourceData B)
```

**2. Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by p-czaja** [comment]
Dear @huiyueun, please take a look.

**Comment by huiyueun** [comment]
Fixed,
https://github.com/dalihub/nui-demo/commit/857372ebdb355ace80d1ad026aa2663694249f49
