### ISSUE TITLE
[HomeApplication] Wrong indicator position after exit edit mode

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#18]
After exit edit mode the indicator is set at first item even if before enter edit mode its position was different.

**Images:**
<img src="https://user-images.githubusercontent.com/35915826/79544265-0a514b80-808f-11ea-9f46-478fc521b5ae.png" height="270"><img src="https://user-images.githubusercontent.com/35915826/79544315-1e954880-808f-11ea-9ede-b642b114abe5.png" height="270"><img src="https://user-images.githubusercontent.com/35915826/79544329-23f29300-808f-11ea-9ab6-d0e7783a3950.png" height="270">

**Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by p-czaja** [comment]
Dear @huiyueun, please take a look.

**Comment by huiyueun** [comment]
After edit mode, it points to the previously selected item.
https://github.com/dalihub/nui-demo/commit/1dcbaf0446752c883cd16502c25f589129e02d81
