### ISSUE TITLE
[HomeApplication] Swipe between pages in edit mode

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#19]
There is no possibility to swipe between pages in edit mode.
**Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
Dear @huiyueun, please take a look.

**Comment by huiyueun** [comment]
Is swipe paging required in Edit mode?
The current page movement is as follows.
1. in edit mode, long press item.
2. Move item to side(left or right) of screen.
3. you can move next/prev page.

**Comment by p-czaja** [comment]
Plain swipe paging is also needed in edit mode - not only by item replacing.

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/commit/c32fa0e5c579e6e4757efecb0458f0faf2bf1c00
