### ISSUE TITLE
[HomeApplication] Distinction between enter edit mode and click item.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#20]
When edit mode is entered if long press gesture on one of the items occurs, the selected and clicked events shouldn't be raised. Only touch gestures shorter than long press should raise the Clicked event.

**Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by p-czaja** [comment]
Dear @huiyueun, please take a look.

**Comment by huiyueun** [comment]
It is fixed, please check latest sample code.
