### ISSUE TITLE
[HomeApplication] Raise events when main text is clicked.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#22]
Clicking to main text should be treated as clicking by currently active item. It concerns both clicked and selected events and enter edit mode (long tap gesture).

**Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
call clicked event when click main text.
https://github.com/dalihub/nui-demo/commit/737d8c9e29a142352d99457e2dfaf07d6ef2f1cf
