### ISSUE TITLE
[HomeApplication] Appending item error.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#23]
1. When trying to add an new rotary selector item error occurs:

<img src="https://user-images.githubusercontent.com/35915826/79866778-94761880-83dd-11ea-82cb-71623b68cd10.png" height="270">
In the picture the last element has been clicked. This should add the new element at the end.

2. **Source code**: [here](https://github.com/p-czaja/nui-demo/tree/addingItem).

3. **Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
Modified by this patch.
https://github.com/dalihub/nui-demo/commit/95d7c4310ec4390cd902dfe425011d760e9ec04f
