### ISSUE TITLE
[HomeApplication] Deleting item error.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#24]
1. When trying to remove one of the rotary selector item error occurs:

<img src="https://user-images.githubusercontent.com/35915826/79868529-529aa180-83e0-11ea-8dfa-2b5fdc487589.png" height="270"> <img src="https://user-images.githubusercontent.com/35915826/79868532-54fcfb80-83e0-11ea-909d-f97170d7c589.png" height="270">
In the first picture the last element has been clicked. This should remove the last item.

2. **Source code**: [here](https://github.com/p-czaja/nui-demo/tree/deletingItem).

3. **Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
Fixex this issue. Please check this patch.
https://github.com/dalihub/nui-demo/commit/95d7c4310ec4390cd902dfe425011d760e9ec04f
