### ISSUE TITLE
[HomeApplication] Swipe between pages issues.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#26]
1. When swiping between pages there is a problem with setting current item.

- 4 pages:
<img src="https://user-images.githubusercontent.com/35915826/80093126-3fb0da00-8564-11ea-8258-5e0cf8be667e.png" height="270"> <img src="https://user-images.githubusercontent.com/35915826/80093142-46d7e800-8564-11ea-96f9-9cc287aa5e24.png" height="270">
Swipe from 1st to 2nd page: Wrong MainText.

- 2 pages:
<img src="https://user-images.githubusercontent.com/35915826/80093587-0a58bc00-8565-11ea-9505-a19a506309e3.png" height="270"> <img src="https://user-images.githubusercontent.com/35915826/80093637-22c8d680-8565-11ea-98be-0b9cf622aba9.png" height="270">  <img src="https://user-images.githubusercontent.com/35915826/80093645-278d8a80-8565-11ea-85e7-c08b2cb71564.png" height="270">
Swipe from 1st to 2nd page    ->    swipe from 2nd to 1st page:
Wrong main text and click event raised on item associated to main text's item.

2. **Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/commit/87bab4e6d83266f5dbb051df2c14dd174db3ad84
