### ISSUE TITLE
[HomeApplication] Long Holding main text throws an exception.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#27]
1. When long holding the main text the NullReferenceException is thrown. This should also enable the edit mode.

2. **Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/commit/70bd075adf5f6cb7936321033413a60aaf55d197
