### ISSUE TITLE
[HomeApplication] Reordered event is not raised.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#28]
1. Reordered event is not raised when rotary selector items are reordered.

2. **Tested on:**
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200403.1;
Release=20200403.1;
[Build]
Type=eng;
Date=20200403_014748;
Time=01:47:48;
Variant=NONE;
ID=tizen-unified;

```

**Comment by huiyueun** [comment]
I have some question about reordered event.
- reorder has not been implemented yet, Is it right that each Rotaryitem has an event?
- Is this event called when the position is changed in editmode?
- Should it be called when append / prepend / delete?

**Comment by p-czaja** [comment]
> reorder has not been implemented yet, Is it right that each Rotaryitem has an event?

Yes I think it is ok. It would be nice if the event args of this event contain previous and current position of the item. Alternative way is event associated to the rotary selector. It that case event args should also contain the reordered item reference.

> Is this event called when the position is changed in editmode?

Yes.

> Should it be called when append / prepend / delete?

No. Reordered event should concern only reordering items. I think deleted event is intended for deleting items in edit mode.

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/42
