### ISSUE TITLE
[HomeApplication][WApps] IsDeleteAble property of RotarySelectorItem doesn't work

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#50]
1. When IsDeleteAble property is set to false and edit mode is activated:
- 'minus icon' is still visible next to the item icon (it shouldn't be visible)
- item icons still can be deleted 
2. Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/58
