### ISSUE TITLE
[HomeApplication][WApps] Raise 'Reordered' event only for moved item

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#52]
1. When Rotary Selector item is moved in Edit mode, the Reordered event is raised for all items that changed its positions. Please change this behavior so that only for the item who made the changes the event is raised.

2. Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun, could you please take a look?

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/60
