### ISSUE TITLE
[HomeApplication][WApps] Page indicators in rotary selector control not curved

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#53]
1. The page inticator (the dots at the top of the screen) are placed on "straight line". The guides show that it is slighty curved.

2. Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun, could you please take a look?

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/78

Below patch of NUI should be applied.
https://github.com/Samsung/TizenFX/pull/1744

this patch is aleady merge on latest tizenfx.
Please use latest binary -> tizen-unified_20200626.2_wearable-emulator-circle
