### ISSUE TITLE
[HomeApplication][WApps] Item can be moved to improper place

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#66]
1. When rotary selector item is moved in edit mode, it may be dropped in the wrong place:
<img src="https://user-images.githubusercontent.com/35915826/85100498-8fc4b980-b200-11ea-9e8e-c528645fdea5.png" height="270">

2. Tested on:

```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun, could you please take a look?

**Comment by huiyueun** [comment]
@p-czaja Could you share the detail scenario?

**Comment by p-czaja** [comment]
Please use the number of elements that cover two pages (i.e. 15). 
Note: Sometimes I notice different behavior when rotary selector has different number of pages of items (tested for 2 vs. 4 pages).

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/76
