### ISSUE TITLE
[HomeApplication][WApps] RemovableItems added in edit mode don't have a 'minus' icon

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#67]
1. Modified sample that shows the issue can be found [here](https://github.com/p-czaja/nui-demo/tree/addingItemInEditMOde). 
2. Steps to reproduce:
    - enable edit mode
    - delete one of the items
    - new item based on removed one will be added by `AppendItem()`. It doesn't have a 'minus' icon.
3. Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun, please take a look.

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/68
