### ISSUE TITLE
[HomeApplication][WApps] Reorder icon issues

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#72]
1. When moving item to next page, back to previous page and leave item, empty place for item appears and reorder event arguments are improper.
2. Steps to reproduce

- run modified sample from [here](https://github.com/p-czaja/nui-demo/tree/reorder_test)  (changed number of items to 11 and added reordered event handler)

- enable edit mode

- move 'Contacts' icon to left page (without dropping it)

- back to previous - right page

- drop the icon for example on the 'Apps' icon.

<img src="https://user-images.githubusercontent.com/35915826/85531566-2cc39000-b60f-11ea-817a-73f922053c29.png" height="270"> <img src="https://user-images.githubusercontent.com/35915826/85531587-31884400-b60f-11ea-84f8-e0fa17b29788.png" height="270">  <img src="https://user-images.githubusercontent.com/35915826/85531602-34833480-b60f-11ea-888b-685358abe6da.png" height="270">

3. Result:

-  empty place for item appeared at the old 'Contacts' icon
- Reordered event sent improper arguments: "Reordered item: Contacts from: 17 to: 2" (should be: from 7 to 2)

3. Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200605.2;
Release=20200605.2;
[Build]
Type=eng;
Date=20200605_215033;
Time=21:50:33;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun, could you please take a look?

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/76
