### ISSUE TITLE
[HomeApplication][WApps] Item deleted during reordering other item.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#74]
1. Steps to reproduce:
    - Run WApps sample app
    - Enable edit mode
    - start reordering one of the items
    - move an item over another - over its minus icon
    - drop item
    - the item at the bottom will be removed
2.  Tested on:
```
cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200623.1;
Release=20200623.1;
[Build]
Type=eng;
Date=20200623_092042;
Time=09:20:42;
Variant=NONE;
ID=tizen-unified;
```

**Comment by p-czaja** [comment]
@huiyueun, could you please take a look?

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/75
