### ISSUE TITLE
[HomeApplication][WApps] Modifying item in inactive page causes improper behavior

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#89]
1. When rotary selector in inactive page is modified it causes improper bahavior.
2 Steps to reproduce:

- Run modified [WApps.](https://github.com/p-czaja/nui-demo/tree/opacityTest)
- swipe to second page
- back to first page
- click any item
3. Result:
<img src="https://user-images.githubusercontent.com/35915826/87054388-54b41580-c203-11ea-9738-9f785d8a3afc.png" height="270">

2. Tested on:

```
 cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200703.2;
Release=20200703.2;
[Build]
Type=eng;
Date=20200703_194937;
Time=19:49:37;
Variant=NONE;
ID=tizen-unified;```

**Comment by p-czaja** [comment]
Dear @huiyueun , please take a look.

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/91
