### ISSUE TITLE
Reordered item disappears when the page changes.

### ISSUE THREAD

**Issue by p-czaja** [dalihub/nui-demo#93]
1. Reordered item disappears when the page changes. It is caused by this [line](https://github.com/dalihub/nui-demo/blob/1b1f3ce2c15876f24323702beabbcf731988bc24/wearable-samples/ReferenceApplication/WApps/RotarySelector/Animation/AnimationManager.cs#L171) added recently.

2. Steps to reproduce:

- Run WApps sample app
- enable edit mode
- start moving one of the items
- change page during moving item.
3. Result: item disappears:

<img src="https://user-images.githubusercontent.com/35915826/87152805-ad90b600-c2b6-11ea-9081-b6fe12ef5c2b.png" height="270">

2. Tested on:

```
 cat /etc/info.ini
[Version]
Model=Tizen6/Unified;
Build=tizen-unified_20200703.2;
Release=20200703.2;
[Build]
Type=eng;
Date=20200703_194937;
Time=19:49:37;
Variant=NONE;
ID=tizen-unified;```

**Comment by p-czaja** [comment]
Dear @huiyueun, please take a look.

**Comment by huiyueun** [comment]
https://github.com/dalihub/nui-demo/pull/94
